name: 'build-test'
on: # rebuild any PRs and main branch changes
  [pull_request]

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: '24'
      - run: |
          npm install
      - run: |
          npm run all
  single-line-comment: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./
        with:
          comment: hello
      - uses: ./
        with:
          comment: hello
  multi-line-comment: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./
        with:
          comment: |
            ## What
            Hello old.
      - uses: ./
        with:
          check-only-first-line: true
          comment: |
            ## What
            Hello new.
      - uses: ./
        with:
          check-only-first-line: true
          comment: |
            ## What No match
            Hello.
